name: Release
on:
  push: { tags: "v[0-9]+.[0-9]+.[0-9]+*" }

jobs:
  github:
    permissions: { contents: write }
    uses: nodenv/.github/.github/workflows/release.yml@v3

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with: { formula-name: nodenv }
        env:
          COMMITTER_TOKEN: ${{ secrets.BOT_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          scope: nodenv
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
